language: cpp

# os:
#  - linux
#  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq cmake spatialite-bin gdal-bin automake postgresql postgresql-server-dev-all; fi
  - wget http://download.osgeo.org/postgis/source/postgis-2.1.8.tar.gz
  - tar -xzf postgis-2.1.8.tar.gz
  - cd postgis-2.1.8 && ./configure 
  - cd postgis-2.1.8 && make -j3 && make install
  - rm -Rf postgis-2.1.8.tar.gz postgis-2.1.8

before_script:
  - cmake


script:
  - make
  - make test
