language: python

sudo: false

addons:
  apt:
    packages:
      - cmake
      - spatialite-bin
      - gdal-bin
      - postgresql
      - postgis
      - python-qt4-dev
      - pyqt4-dev-tools


script:
  - cmake .
  - make
  - PYTHONPATH=$PWD ctest -V
