language: python

sudo: false

addons:
  apt:
    packages:
      - cmake
      - spatialite-bin
      - postgresql
      - postgis
      - python-qt4-dev
      - pyqt4-dev-tools
      - libproj-dev
        #- gdal-bin

install:
  - pip install pyspatialite

script:
  - cmake .
  - make
  - PYTHONPATH=$PWD ctest -V
