language: python

sudo: false

addons:
  apt:
    packages:
      - cmake
      - spatialite-bin
      - postgresql
      - postgis
      - python-qt4-dev
      - pyqt4-dev-tools
      - libproj-dev
        #- gdal-bin
      - apt-file

    #install:
    #- pip install pyspatialite

script:
  - apt-file search proj_api.h
  - cmake .
  - make
  - PYTHONPATH=$PWD ctest -V
