language: python

sudo: false

addons:
  apt:
    packages:
      - cmake
      - spatialite-bin
      - gdal-bin
      - postgresql
      - postgis
      - python-qt4-dev
      - pyqt4-dev-tools
      - python-pyspatialite
      - libproj-dev

install:
  - pip install pyspatialite

script:
  - cmake .
  - make
  - PYTHONPATH=$PWD ctest -V
