language: python

sudo: false

addons:
  apt:
    packages:
      - cmake
      - spatialite-bin
      - gdal-bin
      - postgresql
      - postgis

before_script:
  - cmake

script:
  - make
  - make test
